tests = [ {'description': 'PINA: 0x00 => PORTB: 0x00',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00)],
    },
	{'description': 'PINA: 0xFF => PORTB: 0xFF',
    'steps': [ {'inputs': [('PINA',0xFF)], 'iterations': 5 } ],
    'expected': [('PORTB',0xFF)],
    },
	{'description': 'PINA: 0xF0 => PORTB: 0x0F',
    'steps': [ {'inputs': [('PINA',0xF0)], 'iterations': 5 } ],
    'expected': [('PORTB',0x0F)],
    },
	{'description': 'PINA: 0x0F => PORTB: 0xF0',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTB',0xF0)],
    },
	{'description': 'PINA: 0x3C => PORTB: 0xC3',
    'steps': [ {'inputs': [('PINA',0x3C)], 'iterations': 5 } ],
    'expected': [('PORTB',0xC3)],
    },
	{'description': 'PINA: 0xC3 => PORTB: 0x3C',
    'steps': [ {'inputs': [('PINA',0xC3)], 'iterations': 5 } ],
    'expected': [('PORTB',0x3C)],
    },
]
#watch = ['PORTB']
