tests = [ {'description': 'PINA: 0x00 => PORTB: 0x00, PORTC: 0x00',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00), ('PORTC',0x00)],
    },
	{'description': 'PINA: 0xFF => PORTB: 0x0F, PORTC: 0xF0',
    'steps': [ {'inputs': [('PINA',0xFF)], 'iterations': 5 } ],
    'expected': [('PORTB',0x0F), ('PORTC',0xF0)],
    },
	{'description': 'PINA: 0xF0 => PORTB: 0x0F, PORTC: 0x00',
    'steps': [ {'inputs': [('PINA',0xF0)], 'iterations': 5 } ],
    'expected': [('PORTB',0x0F), ('PORTC',0x00)],
    },
	{'description': 'PINA: 0x0F => PORTB: 0x00, PORTC: 0xF0',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00), ('PORTC',0xF0)],
    },
]
#watch = ['PORTB']
